#!/usr/bin/env python3
"""Writes fold3ds/pokebank/species.lua from PokeAPI's data files
(github.com/PokeAPI/pokeapi, data/v2/csv): every species' English name,
generation and growth rate, and the internal index numbers the Gen 1 (Red)
and Gen 3 (Ruby) cartridges use.  Run when a new generation arrives:
python3 tools/make_pokebank_species.py
"""
import csv, io, os, urllib.request

BASE = "https://raw.githubusercontent.com/PokeAPI/pokeapi/master/data/v2/csv/"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "fold3ds", "pokebank", "species.lua")


def rows(name):
    text = urllib.request.urlopen(BASE + name + ".csv", timeout=60).read().decode("utf-8")
    return csv.DictReader(io.StringIO(text))


def main():
    names = {int(r["pokemon_species_id"]): r["name"] for r in rows("pokemon_species_names") if r["local_language_id"] == "9"}
    grow, gen = {}, {}
    for r in rows("pokemon_species"):
        i = int(r["id"])
        grow[i], gen[i] = int(r["growth_rate_id"]), int(r["generation_id"])
    g1, g3 = {}, {}
    for r in rows("pokemon_game_indices"):
        pid, v, gi = int(r["pokemon_id"]), int(r["version_id"]), int(r["game_index"])
        if pid > max(names):
            continue
        if v == 1:
            g1[gi] = pid
        if v == 7:
            g3[gi] = pid
    n = max(names)
    esc = lambda s: s.replace("\\", "\\\\").replace('"', '\\"')
    out = ["-- Generated by tools/make_pokebank_species.py from PokeAPI's data",
           "-- (github.com/PokeAPI/pokeapi, data/v2/csv): every species to #%d with" % n,
           "-- its English name, generation and growth rate, and the internal index",
           "-- numbers the Gen 1 and Gen 3 cartridges use (Gen 2 uses the National Dex).",
           "local S = {}", "S.COUNT = %d" % n, "S.NAME = {"]
    out += ['  "%s",' % esc(names.get(i, "#%d" % i)) for i in range(1, n + 1)]
    out.append("}")
    out.append("S.GEN = { " + ", ".join(str(gen.get(i, 0)) for i in range(1, n + 1)) + " }")
    out.append("-- 1 slow, 2 medium fast, 3 fast, 4 medium slow, 5 erratic, 6 fluctuating")
    out.append("S.GROWTH = { " + ", ".join(str(grow.get(i, 2)) for i in range(1, n + 1)) + " }")
    out.append("S.GEN1_INDEX = { " + ", ".join("[%d] = %d" % (k, g1[k]) for k in sorted(g1)) + " }")
    out.append("S.GEN3_INDEX = { " + ", ".join("[%d] = %d" % (k, g3[k]) for k in sorted(g3)) + " }")
    out.append("return S")
    open(OUT, "w", encoding="utf-8").write("\n".join(out) + "\n")
    print(n, "species")


if __name__ == "__main__":
    main()
