-- three species covering the evolve/learnset/tmhm seams
return {
  FIXMON_A = {
    id = "FIXMON_A", index = 1, dex = 1, name = "FIXMON A",
    types = { "GRASS" },
    baseStats = { hp = 45, attack = 49, defense = 49, speed = 45, special = 65 },
    catchRate = 45, baseExp = 64,
    level1Moves = { "FIX_TACKLE" },
    growthRate = "MEDIUM_SLOW",
    tmhm = { "FIX_CUT" },
    learnset = {
      { level = 1, move = "FIX_TACKLE" },
      { level = 7, move = "FIX_EMBERISH" },
    },
    evolutions = { { method = "LEVEL", level = 16, species = "FIXMON_B" } },
    spriteFront = "tests/fixture_data/assets/fixmon_a_front.png",
    spriteBack = "tests/fixture_data/assets/fixmon_a_back.png",
    frontSize = 5,
    dexEntry = { kind = "SEED", heightFt = 2, heightIn = 4, weight = 150,
                 text = "A fixture." },
  },
  FIXMON_B = {
    id = "FIXMON_B", index = 2, dex = 2, name = "FIXMON B",
    types = { "FIRE" },
    baseStats = { hp = 39, attack = 52, defense = 43, speed = 65, special = 60 },
    catchRate = 45, baseExp = 65,
    level1Moves = { "FIX_SCRATCH" },
    growthRate = "MEDIUM_SLOW",
    tmhm = {},
    learnset = { { level = 1, move = "FIX_SCRATCH" } },
    evolutions = {},
    spriteFront = "tests/fixture_data/assets/fixmon_b_front.png",
    spriteBack = "tests/fixture_data/assets/fixmon_b_back.png",
    frontSize = 5,
    dexEntry = { kind = "FLAME", heightFt = 2, heightIn = 0, weight = 190,
                 text = "A fixture." },
  },
  FIXMON_C = {
    id = "FIXMON_C", index = 3, dex = 3, name = "FIXMON C",
    types = { "WATER" },
    baseStats = { hp = 44, attack = 48, defense = 65, speed = 43, special = 50 },
    catchRate = 45, baseExp = 66,
    level1Moves = { "FIX_TACKLE" },
    growthRate = "MEDIUM_SLOW",
    tmhm = { "FIX_CUT" },
    learnset = { { level = 1, move = "FIX_TACKLE" } },
    evolutions = {},
    spriteFront = "tests/fixture_data/assets/fixmon_c_front.png",
    spriteBack = "tests/fixture_data/assets/fixmon_c_back.png",
    frontSize = 5,
    dexEntry = { kind = "TINY", heightFt = 1, heightIn = 8, weight = 200,
                 text = "A fixture." },
  },
}
